PROG = openxcom.dge
SRCS = $(wildcard *.cpp)
OBJS = $(SRCS:.cpp=.o)
CXX  = mipsel-linux-g++
SDL-CONFIG = /opt/mipsel-linux-uclibc/usr/bin/sdl-config

CXXFLAGS = -Wall -O2 `$(SDL-CONFIG) --cflags` -DDINGOO
LDFLAGS = `$(SDL-CONFIG) --libs` -lSDL_gfx -lSDL_mixer

$(PROG): $(OBJS)
	$(CXX) $(OBJS) $(LDFLAGS) -o $(PROG)

clean:
	rm -f $(PROG) *.o

.PHONY: clean