/*
 * Copyright 2010-2014 OpenXcom Developers.
 *
 * This file is part of OpenXcom.
 *
 * OpenXcom is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenXcom is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenXcom.  If not, see <http://www.gnu.org/licenses/>.
 */
#ifndef OPENXCOM_SAVECONVERTERXCOM1_H
#define OPENXCOM_SAVECONVERTERXCOM1_H

namespace OpenXcom
{
	// Mappings between X-COM 1 IDs and OpenXcom string IDs.

	const char *xcom1Items[] =
	{
		"STR_STINGRAY_LAUNCHER",
		"STR_AVALANCHE_LAUNCHER",
		"STR_CANNON",
		"STR_FUSION_BALL_LAUNCHER",
		"STR_LASER_CANNON",
		"STR_PLASMA_BEAM",
		"STR_STINGRAY_MISSILES",
		"STR_AVALANCHE_MISSILES",
		"STR_CANNON_ROUNDS_X50",
		"STR_FUSION_BALL",
		"STR_TANK_CANNON",
		"STR_TANK_ROCKET_LAUNCHER",
		"STR_TANK_LASER_CANNON",
		"STR_HOVERTANK_PLASMA",
		"STR_HOVERTANK_LAUNCHER",
		"STR_PISTOL",
		"STR_PISTOL_CLIP",
		"STR_RIFLE",
		"STR_RIFLE_CLIP",
		"STR_HEAVY_CANNON",
		"STR_HC_AP_AMMO",
		"STR_HC_HE_AMMO",
		"STR_HC_I_AMMO",
		"STR_AUTO_CANNON",
		"STR_AC_AP_AMMO",
		"STR_AC_HE_AMMO",
		"STR_AC_I_AMMO",
		"STR_ROCKET_LAUNCHER",
		"STR_SMALL_ROCKET",
		"STR_LARGE_ROCKET",
		"STR_INCENDIARY_ROCKET",
		"STR_LASER_PISTOL",
		"STR_LASER_RIFLE",
		"STR_HEAVY_LASER",
		"STR_GRENADE",
		"STR_SMOKE_GRENADE",
		"STR_PROXIMITY_GRENADE",
		"STR_HIGH_EXPLOSIVE",
		"STR_MOTION_SCANNER",
		"STR_MEDI_KIT",
		"STR_PSI_AMP",
		"STR_STUN_ROD",
		"STR_ELECTRO_FLARE",
		"",
		"",
		"",
		"STR_CORPSE",
		"STR_CORPSE_ARMOUR",
		"STR_CORPSE_SUIT",
		"STR_HEAVY_PLASMA",
		"STR_HEAVY_PLASMA_CLIP",
		"STR_PLASMA_RIFLE",
		"STR_PLASMA_RIFLE_CLIP",
		"STR_PLASMA_PISTOL",
		"STR_PLASMA_PISTOL_CLIP",
		"STR_BLASTER_LAUNCHER",
		"STR_BLASTER_BOMB",
		"STR_SMALL_LAUNCHER",
		"STR_STUN_BOMB",
		"STR_ALIEN_GRENADE",
		"STR_ELERIUM_115",
		"STR_MIND_PROBE",
		"",
		"",
		"",
		"STR_SECTOID_CORPSE",
		"STR_SNAKEMAN_CORPSE",
		"STR_ETHEREAL_CORPSE",
		"STR_MUTON_CORPSE",
		"STR_FLOATER_CORPSE",
		"STR_CELATID_CORPSE",
		"STR_SILACOID_CORPSE",
		"STR_CHRYSSALID_CORPSE",
		"STR_REAPER_CORPSE",
		"STR_SECTOPOD_CORPSE",
		"STR_CYBERDISC_CORPSE",
		"STR_HOVERTANK_CORPSE",
		"STR_TANK_CORPSE",
		"STR_CIVM_CORPSE",
		"STR_CIVF_CORPSE",
		"STR_UFO_POWER_SOURCE",
		"STR_UFO_NAVIGATION",
		"STR_UFO_CONSTRUCTION",
		"STR_ALIEN_FOOD",
		"STR_ALIEN_REPRODUCTION",
		"STR_ALIEN_ENTERTAINMENT",
		"STR_ALIEN_SURGERY",
		"STR_EXAMINATION_ROOM",
		"STR_ALIEN_ALLOYS",
		"STR_ALIEN_HABITAT",
		"STR_PERSONAL_ARMOR",
		"STR_POWER_SUIT",
		"STR_FLYING_SUIT",
		"STR_HWP_CANNON_SHELLS",
		"STR_HWP_ROCKETS",
		"STR_HWP_FUSION_BOMB"
	};
}

#endif
