option ( DEBIAN_DEPENDENCYS "Create RPM with dependency rules for Debian" OFF )
set ( CPACK_DEBIAN_PACKAGE_MAINTAINER "The OpenXcom project" )
if ( DEBIAN_DEPENDENCYS )
  set ( CPACK_DEBIAN_PACKAGE_DEPENDS "libsdl1.2 (>= 1.2.14-6.1), libsdl-gfx1.2 (>= 2.0.20), libsdl-mixer1.2 (>= 1.2.8)")
endif ()
set ( CPACK_DEBIAN_PACKAGE_ARCHITECTURE ${CMAKE_SYSTEM_PROCESSOR} )
