'\" t
.\"     Title: openxcom
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 2014.06.12
.\"    Manual: User\*(Aqs Manual
.\"    Source: 1.0
.\"  Language: English
.\"
.TH "OPENXCOM" "6" "2014\&.06\&.12" "1\&.0" "User\*(Aqs Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
openxcom \- An open\-source clone of the original "UFO: Enemy Unknown"
.SH "SYNOPSIS"
.HP \w'\fBopenxcom\fR\ 'u
\fBopenxcom\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
.PP
\fBopenxcom\fR
is an open\-source clone of the popular UFO: Enemy Unknown (X\-Com: UFO Defense in USA) videogame by Microprose, licensed under the GPL and written in C++ / SDL\&.
.SH "OPTIONS"
.PP
\fB\-data\fR \fIPATH\fR
.RS 4
use
\fIPATH\fR
as the default Data Folder instead of auto\-detecting
.RE
.PP
\fB\-user\fR \fIPATH\fR
.RS 4
use
\fIPATH\fR
as the default User Folder instead of auto\-detecting
.RE
.PP
\fB\-cfg\fR \fIPATH\fR
.RS 4
use
\fIPATH\fR
as the default Config Folder instead of auto\-detecting
.RE
.PP
\fB\-\fR\fB\fIKEY\fR\fR \fIVALUE\fR
.RS 4
set option
\fIKEY\fR
to
\fIVALUE\fR
instead of default/loaded value (eg\&.
\-displayWidth 640)
.RE
.PP
\fB\-help\fR, \fB\-?\fR
.RS 4
show command\-line help
.RE
.SH "AUTHOR"
.PP
OpenXcom Developers
.SH "SEE ALSO"
.PP
\m[blue]\fB\%https://openxcom.org\fR\m[],
\m[blue]\fB\%http://ufopaedia.org/index.php?title=OpenXcom\fR\m[]
.SH "COPYRIGHT"
.br
Copyright \(co 2014 OpenXcom Developers
.br
