.Dd 2014-06-12
.Dt OPENXCOM 6
.Os
.Sh NAME
.Nm openxcom
.Nd An open-source reimplementation of the original
.Dq UFO: Enemy Unknown
game
.Sh SYNOPSIS
.Nm
.Op Fl ? | help
.Op Fl data Ar path
.Op Fl user Ar path
.Op Fl cfg Ar path
.Op Fl master Ar mod
.Op Fl KEY Ar VALUE
.Sh DESCRIPTION
.Nm openxcom
is an open-source reimplementation of the popular
.Dq UFO: Enemy Unknown
game also known as
.Dq X-COM: UFO Defense
in North America, and its sequel
.Dq X-COM: Terror from the Deep
by publisher
.An MicroProse .
It is licensed under the GPL and written in C++ / SDL.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl ?, Fl help
show command-line help
.It Fl data Ar path
use
.Ar path
as the default Data Folder instead of auto-detecting
.It Fl user Ar path
use
.Ar path
as the default User Folder instead of auto-detecting
.It Fl cfg Ar path
use
.Ar path
as the default Config Folder instead of auto-detecting
.It Fl master Ar mod
set
.Ar mod
the current master mod (eg.\&
.Fl master
.Ar xcom2 )
.It Fl KEY Ar VALUE
set option
.Ar KEY
to
.Ar VALUE
instead of default/loaded value (eg\&.
.Fl displayWidth
.Ar 640
).
See
.Pa src/Engine/Options.cpp
for a list of all potential options.
.El
.Sh INSTALLATION
.Nm OpenXcom
requires a vanilla copy of the X-COM resources \(em from either or both of the original games.
Please refer to the
.Pa README.md
for the default search paths and the exact directory layout, as well as information on the Mod support.
.Sh SEE ALSO
.Lk https://openxcom.org ,
.Lk https://ufopaedia.org/index.php?title=OpenXcom
.Sh HISTORY
.An MicroProse
releases
.Dq UFO: Enemy Unknown
in 1994, followed by
.Dq X-COM: Terror from the Deep
in 1995 with various sequels following.
The
.Nm OpenXcom
project sees the light of day in 2010.
.Sh COPYRIGHT
Copyright \(co 2020 OpenXcom Developers
.Sh AUTHORS
.An OpenXcom Developers
